// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: my2.proto

#ifndef PROTOBUF_my2_2eproto__INCLUDED
#define PROTOBUF_my2_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_my2_2eproto();
void protobuf_AssignDesc_my2_2eproto();
void protobuf_ShutdownFile_my2_2eproto();

class LogonReqMessage2;

// ===================================================================

class LogonReqMessage2 : public ::google::protobuf::Message {
 public:
  LogonReqMessage2();
  virtual ~LogonReqMessage2();

  LogonReqMessage2(const LogonReqMessage2& from);

  inline LogonReqMessage2& operator=(const LogonReqMessage2& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LogonReqMessage2& default_instance();

  void Swap(LogonReqMessage2* other);

  // implements Message ----------------------------------------------

  inline LogonReqMessage2* New() const { return New(NULL); }

  LogonReqMessage2* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LogonReqMessage2& from);
  void MergeFrom(const LogonReqMessage2& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LogonReqMessage2* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string passwd2 = 2;
  bool has_passwd2() const;
  void clear_passwd2();
  static const int kPasswd2FieldNumber = 2;
  const ::std::string& passwd2() const;
  void set_passwd2(const ::std::string& value);
  void set_passwd2(const char* value);
  void set_passwd2(const char* value, size_t size);
  ::std::string* mutable_passwd2();
  ::std::string* release_passwd2();
  void set_allocated_passwd2(::std::string* passwd2);

  // required int64 acctID2 = 1;
  bool has_acctid2() const;
  void clear_acctid2();
  static const int kAcctID2FieldNumber = 1;
  ::google::protobuf::int64 acctid2() const;
  void set_acctid2(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:LogonReqMessage2)
 private:
  inline void set_has_passwd2();
  inline void clear_has_passwd2();
  inline void set_has_acctid2();
  inline void clear_has_acctid2();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr passwd2_;
  ::google::protobuf::int64 acctid2_;
  friend void  protobuf_AddDesc_my2_2eproto();
  friend void protobuf_AssignDesc_my2_2eproto();
  friend void protobuf_ShutdownFile_my2_2eproto();

  void InitAsDefaultInstance();
  static LogonReqMessage2* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// LogonReqMessage2

// required string passwd2 = 2;
inline bool LogonReqMessage2::has_passwd2() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LogonReqMessage2::set_has_passwd2() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LogonReqMessage2::clear_has_passwd2() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LogonReqMessage2::clear_passwd2() {
  passwd2_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_passwd2();
}
inline const ::std::string& LogonReqMessage2::passwd2() const {
  // @@protoc_insertion_point(field_get:LogonReqMessage2.passwd2)
  return passwd2_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LogonReqMessage2::set_passwd2(const ::std::string& value) {
  set_has_passwd2();
  passwd2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:LogonReqMessage2.passwd2)
}
inline void LogonReqMessage2::set_passwd2(const char* value) {
  set_has_passwd2();
  passwd2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:LogonReqMessage2.passwd2)
}
inline void LogonReqMessage2::set_passwd2(const char* value, size_t size) {
  set_has_passwd2();
  passwd2_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:LogonReqMessage2.passwd2)
}
inline ::std::string* LogonReqMessage2::mutable_passwd2() {
  set_has_passwd2();
  // @@protoc_insertion_point(field_mutable:LogonReqMessage2.passwd2)
  return passwd2_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LogonReqMessage2::release_passwd2() {
  clear_has_passwd2();
  return passwd2_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LogonReqMessage2::set_allocated_passwd2(::std::string* passwd2) {
  if (passwd2 != NULL) {
    set_has_passwd2();
  } else {
    clear_has_passwd2();
  }
  passwd2_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), passwd2);
  // @@protoc_insertion_point(field_set_allocated:LogonReqMessage2.passwd2)
}

// required int64 acctID2 = 1;
inline bool LogonReqMessage2::has_acctid2() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LogonReqMessage2::set_has_acctid2() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LogonReqMessage2::clear_has_acctid2() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LogonReqMessage2::clear_acctid2() {
  acctid2_ = GOOGLE_LONGLONG(0);
  clear_has_acctid2();
}
inline ::google::protobuf::int64 LogonReqMessage2::acctid2() const {
  // @@protoc_insertion_point(field_get:LogonReqMessage2.acctID2)
  return acctid2_;
}
inline void LogonReqMessage2::set_acctid2(::google::protobuf::int64 value) {
  set_has_acctid2();
  acctid2_ = value;
  // @@protoc_insertion_point(field_set:LogonReqMessage2.acctID2)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_my2_2eproto__INCLUDED
